import Head from 'next/head'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='my-12 text-lg font-medium'>
        <h2 className='text-2xl'>See how other people are feeling</h2>
      </div>

    </div>
  )
}
